### ISSUE TITLE
Create the ThreadsService

### ISSUE THREAD

**Issue by andrerpena** [matterspace/matterspace#12]
@AdowTatep , on commit 4db4a7edf95696eac259b81f16d233c8eb5488dd you made this:

![image](https://cloud.githubusercontent.com/assets/1581429/22392239/4359ba2a-e4de-11e6-8bf8-93178e1ae75a.png)

This is loading up all threads from a Product. This is **extremely expensive**. We should have a `ThreadsService` with methods like

- `GetIdeas(Status status...)`
- `GetIssues(Status...)`
- ...

The parameters of the above methods will **depend** on that is actually needed. I can't predict now. This should be empiric.

**Comment by andrerpena** [comment]
As a side note. It's **very important** that every Service method that returns a list should receive a `page` parameter and should only return items from that page. This means that the `Count` won't work anymore. We need methods specifically for returning counts.

**Comment by AdowTatep** [comment]
The thread service is already getting threads by its type and its id, I just made the parameter optional for testing the final purpose of counting the number of threads in screen and then I committed so Thiago could see how it was. But since it wasn't the final version I didn't closed the issue #6. 

Following this issue, the thread sevice's "get threads" now requires the "thread type" parameter and the count is a query only for that purpose that fills an IEnumerable of counts, in a way that if new thread type shows up, it'll be already covered since there won't be need to add a new property in the product view model
