### ISSUE TITLE
Make sure we're always using UTC dates

### ISSUE THREAD

**Issue by andrerpena** [matterspace/matterspace#13]
Flanjos would probably bitch about it but there's no need for `DateTimeOffset` here because:

- MS is not a multi-tenant app that is expected to display dates according to where a tenant is located. It's acceptable that dates are displayed in a particular way when we're talking about global websites like GH and SO.
- Dates will almost always be displayed in a relative way (22 minutes ago, 14 days ago) rather than in an absolute way. I just made a little research and I didn't find a single place where GH displays dates in an absolute way. Display dates relatively has some advantages: 1) You don't have to deal with time-zones and DLST. 2) You don't have to deal with time-formats.

**BUT**, we also cannot store `DateTime.Now()` on the DB, never, because this will be affected by where the server is located. Even within Windows Azure, `DateTime.Now()` will vary depending on which **region** we're talking about.

For that reason, every  `DateTime.Now()` being stored on the DB should be replaced by  `DateTime.UtcNow()` and every operation should take this into account.

**Comment by AdowTatep** [comment]
> I just made a little research and I didn't find a single place where GH displays dates in an absolute way

Github shows them in releases page, and we should check if we could do it there too, since for releases, it's good to differ them with dates and I think its easier too.

It's better to see if X thing was released at 01/29/2017 and the Y was in 01/01/2017 than looking at a release with "1 day ago" and "1 month ago".

And even though we're not using offset. Since everything is UTC, we can just subtract or sum the UTC time with the current user's timezone

@andrerpena we could discuss this
